// Code generated by scripts/generate_types.py; DO NOT EDIT.

export const CLOUD_NEWS_SOURCES = ["aws", "google-cloud", "azure", "oci", "other"] as const;
export type CloudNewsSource = (typeof CLOUD_NEWS_SOURCES)[number];

